In [10]:
# loaded required libraries
import pandas as pd

In [11]:
# importing required datasets
marketing = pd.read_csv('dataset/marketing.csv')
orders = pd.read_csv('dataset/orders.csv')

In [12]:
orders.head()

,order_id,order_date,order_time,customer_id,store_id,campaign_id,total_amount,delivery_fee,discount_amount,net_revenue,payment_method,delivery_duration_minutes,delivery_rating,order_status,is_festival_day,bengali_household
0,KOL_ORD_000001,2024-01-01,08:29:51,KOL_CUST_006904,BLK_KOL_009,NaN,2544.97,0,67.91,2477.06,UPI,40,4.3,Delivered,True,True
1,KOL_ORD_000002,2024-01-01,08:00:06,KOL_CUST_006827,BLK_KOL_047,NaN,248.39,0,4.20,244.19,UPI,34,4.1,Delivered,True,True
2,KOL_ORD_000003,2024-01-01,08:18:50,KOL_CUST_003173,BLK_KOL_025,NaN,202.71,30,0.08,232.63,Cash on Delivery,41,3.9,Delivered,True,True
3,KOL_ORD_000004,2024-01-01,08:57:41,KOL_CUST_003899,BLK_KOL_008,NaN,1322.24,30,52.43,1299.81,UPI,43,3.9,Delivered,True,True
4,KOL_ORD_000005,2024-01-01,08:34:30,KOL_CUST_000759,BLK_KOL_038,NaN,1969.24,30,67.39,1931.85,Cash on Delivery,31,4.9,Delivered,True,True

In [13]:
marketing.head()

,campaign_id,campaign_name,start_date,end_date,discount_type,discount_value,target_region,campaign_budget,festival_focus
0,KOL_DURGA_2024,Durga Puja Special,2024-10-05,2024-10-15,Percentage,30,East,10000000,Durga Puja
1,KOL_KALI_2024,Kali Puja Bonanza,2024-10-31,2024-11-02,Percentage,25,East,5000000,Kali Puja
2,KOL_POHELA_2024,Pohela Boishakh,2024-04-14,2024-04-16,Flat,150,East,4000000,Bengali New Year
3,KOL_SARASWATI_2024,Saraswati Puja,2024-02-14,2024-02-14,Percentage,20,East,3000000,Saraswati Puja
4,KOL_SUMMER_2024,Kolkata Summer Special,2024-04-01,2024-06-15,Percentage,15,East,8000000,Summer

In [14]:
orders = orders.drop(columns=['campaign_id'], errors='ignore')  # dropping the false column

orders['order_date'] = pd.to_datetime(orders['order_date'],format='%Y-%m-%d',errors='coerce')  # editing the date data type

In [15]:
orders.head()

,order_id,order_date,order_time,customer_id,store_id,total_amount,delivery_fee,discount_amount,net_revenue,payment_method,delivery_duration_minutes,delivery_rating,order_status,is_festival_day,bengali_household
0,KOL_ORD_000001,2024-01-01,08:29:51,KOL_CUST_006904,BLK_KOL_009,2544.97,0,67.91,2477.06,UPI,40,4.3,Delivered,True,True
1,KOL_ORD_000002,2024-01-01,08:00:06,KOL_CUST_006827,BLK_KOL_047,248.39,0,4.20,244.19,UPI,34,4.1,Delivered,True,True
2,KOL_ORD_000003,2024-01-01,08:18:50,KOL_CUST_003173,BLK_KOL_025,202.71,30,0.08,232.63,Cash on Delivery,41,3.9,Delivered,True,True
3,KOL_ORD_000004,2024-01-01,08:57:41,KOL_CUST_003899,BLK_KOL_008,1322.24,30,52.43,1299.81,UPI,43,3.9,Delivered,True,True
4,KOL_ORD_000005,2024-01-01,08:34:30,KOL_CUST_000759,BLK_KOL_038,1969.24,30,67.39,1931.85,Cash on Delivery,31,4.9,Delivered,True,True

In [18]:
orders_base = orders.copy()

orders['key'] = 1
marketing['key'] = 1

df = orders_base.merge(marketing, on='key', how='left')

In [20]:
df = df[
    (df['order_date']>=df['start_date']) &
    (df['order_date']<=df['end_date'])
]

In [21]:
df.head()

,order_id,order_date,order_time,customer_id,store_id,total_amount,delivery_fee,discount_amount,net_revenue,payment_method,...,key,campaign_id,campaign_name,start_date,end_date,discount_type,discount_value,target_region,campaign_budget,festival_focus
4585,KOL_ORD_000510,2024-04-01,08:56:36,KOL_CUST_006311,BLK_KOL_018,643.94,0,61.22,582.72,UPI,...,1,KOL_SUMMER_2024,Kolkata Summer Special,2024-04-01,2024-06-15,Percentage,15,East,8000000,Summer
4594,KOL_ORD_000511,2024-04-01,08:50:34,KOL_CUST_002780,BLK_KOL_017,687.24,30,56.85,660.39,Cash on Delivery,...,1,KOL_SUMMER_2024,Kolkata Summer Special,2024-04-01,2024-06-15,Percentage,15,East,8000000,Summer
4603,KOL_ORD_000512,2024-04-01,08:43:46,KOL_CUST_002353,BLK_KOL_021,876.43,0,103.17,773.26,Cash on Delivery,...,1,KOL_SUMMER_2024,Kolkata Summer Special,2024-04-01,2024-06-15,Percentage,15,East,8000000,Summer
4612,KOL_ORD_000513,2024-04-01,08:32:18,KOL_CUST_001103,BLK_KOL_033,792.08,30,86.03,736.05,UPI,...,1,KOL_SUMMER_2024,Kolkata Summer Special,2024-04-01,2024-06-15,Percentage,15,East,8000000,Summer
4621,KOL_ORD_000514,2024-04-01,08:29:51,KOL_CUST_003273,BLK_KOL_040,1849.47,30,8.82,1870.65,Cash on Delivery,...,1,KOL_SUMMER_2024,Kolkata Summer Special,2024-04-01,2024-06-15,Percentage,15,East,8000000,Summer

In [22]:
df = (
    df.sort_values(['order_id','start_date'], ascending=[True,False])
    .drop_duplicates('order_id')
)

In [23]:
orders = orders_base.merge(
    df[['order_id','campaign_id']],
    on='order_id',
    how='left'
)

In [24]:
orders = orders.drop(columns=['key'],errors='ignore')
marketing = marketing.drop(columns=['key'],errors='ignore')

In [25]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 73591 entries, 0 to 73590
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   73591 non-null  str
 1   order_date                 73591 non-null  datetime64[us]
 2   order_time                 73591 non-null  str
 3   customer_id                73591 non-null  str
 4   store_id                   73591 non-null  str
 5   total_amount               73591 non-null  float64
 6   delivery_fee               73591 non-null  int64
 7   discount_amount            73591 non-null  float64
 8   net_revenue                73591 non-null  float64
 9   payment_method             73591 non-null  str
 10  delivery_duration_minutes  73591 non-null  int64
 11  delivery_rating            73591 non-null  float64
 12  order_status               73591 non-null  str
 13  is_festival_day            73591 non-null  bool
 14  bengali_household          73591 non-null  bool
 15  campaign_id                44560 non-null  str
dtypes: bool(2), datetime64[us](1), float64(4), int64(2), str(7)
memory usage: 8.0 MB

In [26]:
orders.to_csv('dataset/orders.csv',index=False)

In [27]:
orders = orders.merge(marketing[['campaign_id','discount_type','discount_value']], on='campaign_id',how='left')

In [28]:
orders.head()

,order_id,order_date,order_time,customer_id,store_id,total_amount,delivery_fee,discount_amount,net_revenue,payment_method,delivery_duration_minutes,delivery_rating,order_status,is_festival_day,bengali_household,campaign_id,discount_type,discount_value
0,KOL_ORD_000001,2024-01-01,08:29:51,KOL_CUST_006904,BLK_KOL_009,2544.97,0,67.91,2477.06,UPI,40,4.3,Delivered,True,True,NaN,NaN,NaN
1,KOL_ORD_000002,2024-01-01,08:00:06,KOL_CUST_006827,BLK_KOL_047,248.39,0,4.20,244.19,UPI,34,4.1,Delivered,True,True,NaN,NaN,NaN
2,KOL_ORD_000003,2024-01-01,08:18:50,KOL_CUST_003173,BLK_KOL_025,202.71,30,0.08,232.63,Cash on Delivery,41,3.9,Delivered,True,True,NaN,NaN,NaN
3,KOL_ORD_000004,2024-01-01,08:57:41,KOL_CUST_003899,BLK_KOL_008,1322.24,30,52.43,1299.81,UPI,43,3.9,Delivered,True,True,NaN,NaN,NaN
4,KOL_ORD_000005,2024-01-01,08:34:30,KOL_CUST_000759,BLK_KOL_038,1969.24,30,67.39,1931.85,Cash on Delivery,31,4.9,Delivered,True,True,NaN,NaN,NaN

In [29]:
orders['discount_amount'] = 0.0

# masks
percentage_mask = orders['discount_type'] == 'Percentage'
flat_mask = orders['discount_type'] == 'Flat'

# calculating discount amount
orders.loc[percentage_mask,'discount_amount'] = (orders.loc[percentage_mask,'total_amount'] * orders.loc[percentage_mask,'discount_value'] / 100)  # percentage discount
orders.loc[flat_mask,'discount_amount'] = orders.loc[flat_mask,'discount_value']  # flat discount

orders['discount_amount'] = orders[['total_amount','discount_amount']].min(axis=1)

In [30]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 73591 entries, 0 to 73590
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   73591 non-null  str
 1   order_date                 73591 non-null  datetime64[us]
 2   order_time                 73591 non-null  str
 3   customer_id                73591 non-null  str
 4   store_id                   73591 non-null  str
 5   total_amount               73591 non-null  float64
 6   delivery_fee               73591 non-null  int64
 7   discount_amount            73591 non-null  float64
 8   net_revenue                73591 non-null  float64
 9   payment_method             73591 non-null  str
 10  delivery_duration_minutes  73591 non-null  int64
 11  delivery_rating            73591 non-null  float64
 12  order_status               73591 non-null  str
 13  is_festival_day            73591 non-null  bool
 14  bengali_household          73591 non-null  bool
 15  campaign_id                44560 non-null  str
 16  discount_type              44560 non-null  str
 17  discount_value             44560 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(5), int64(2), str(8)
memory usage: 9.1 MB

In [31]:
orders['net_revenue'] = orders['total_amount'] + orders['delivery_fee'] - orders['discount_amount']

In [32]:
orders.head()

,order_id,order_date,order_time,customer_id,store_id,total_amount,delivery_fee,discount_amount,net_revenue,payment_method,delivery_duration_minutes,delivery_rating,order_status,is_festival_day,bengali_household,campaign_id,discount_type,discount_value
0,KOL_ORD_000001,2024-01-01,08:29:51,KOL_CUST_006904,BLK_KOL_009,2544.97,0,0.0,2544.97,UPI,40,4.3,Delivered,True,True,NaN,NaN,NaN
1,KOL_ORD_000002,2024-01-01,08:00:06,KOL_CUST_006827,BLK_KOL_047,248.39,0,0.0,248.39,UPI,34,4.1,Delivered,True,True,NaN,NaN,NaN
2,KOL_ORD_000003,2024-01-01,08:18:50,KOL_CUST_003173,BLK_KOL_025,202.71,30,0.0,232.71,Cash on Delivery,41,3.9,Delivered,True,True,NaN,NaN,NaN
3,KOL_ORD_000004,2024-01-01,08:57:41,KOL_CUST_003899,BLK_KOL_008,1322.24,30,0.0,1352.24,UPI,43,3.9,Delivered,True,True,NaN,NaN,NaN
4,KOL_ORD_000005,2024-01-01,08:34:30,KOL_CUST_000759,BLK_KOL_038,1969.24,30,0.0,1999.24,Cash on Delivery,31,4.9,Delivered,True,True,NaN,NaN,NaN

In [33]:
orders.shape

(73591, 18)

In [34]:
orders = orders.drop(columns=['discount_type','discount_value'])

In [35]:
print(orders['campaign_id'].isna().sum())  # to check if there are orders with no campaign ids

29031

In [36]:
orders.to_csv('dataset/orders.csv',index=False)